### ISSUE TITLE
Add a place to track Drones

### ISSUE THREAD

**Issue by Karlinator** [Karlinator/roll20-character-sheets#17]
My current thinking is that this will come as a new header/section in the character sheet.

Other possibility is to put it under gear, but it's a pretty big section to add into gear like that. Also it's kind of separate from normal gear.

**Comment by PanzerUXI** [comment]
The new sheet I'm making has affordances at the top for "Character, Ship, Drone, Faction, X (Shell maybe)". They are very simple mechanically - hull + fittings(x) + name + TL they can operate in before Quantum ECM disables.

This brings up a good point though, re: Gear & Modifications. Modifications change the whole sheet because it touches all sorts of systems, even drones. Equipment, Drones, Mechs, Ships, etc. At least in my games, the Fixer engineer wants to tinker with everything hah.

**Comment by joesinghaus** [comment]
Okay, so "Drone" comes as a new type, same as character, ship, or NPC? We can do that.

**Comment by PanzerUXI** [comment]
Ya I think that's the best way to scale this. 1 sheet can be any single Character Actor. Globally, they are either PC or NPC. Locally, they are either Character, Ship, Drone, Faction, etc etc.

**Comment by joesinghaus** [comment]
I think there's some significant advantage here to make this a repeating section instead, and I'm currently leaning towards that. It makes it a whole lot more straightforward to use the skills of their commander, and I think this is more natural than 1 sheet per drone.

Adding to that is the fact that drones don't have a lot of attributes. It's essentially just

* Name
* Number of fittings
* AC
* Enc
* HP
* Range
* Fittings 1-5

We can still make it a separate tab.

**Comment by joesinghaus** [comment]
Drone tab is established, but still missing autofill data.
