### ISSUE TITLE
[Partly Deluxe]Add a way to represent other vehicles (Engines of Babylon cars, tanks, etc).

### ISSUE THREAD

**Issue by Karlinator** [Karlinator/roll20-character-sheets#18]

**Comment by Karlinator** [comment]
We won't be able to do autofilling on all of this, because the vehicles in Engines of Babylon for instance are part of a paid book.

**Comment by PanzerUXI** [comment]
Let me read up on how EoB and other vehicles are represented and find the commonalities for a sheet. Is there is value in making a new tab called "Custom" where we support these paid supplement objects?

**Comment by joesinghaus** [comment]
Vehicles all seem to be pretty similar ships, I think it would make more sense to treat these as modifications of the Ship tab.

**Comment by joesinghaus** [comment]
Looks like vehicles from the core book are pretty much simpler ships, they do not have AC, just armor. Renaming the tab and maybe hiding all the fields they do not have should suffice. 
Engines of Babylon vehicles do not have AC either. They have size and ground speed instead.

Both of them just have a crew value instead of min and max. There's also some special considerations for tank armor in both cases, which is effectively infinite unless targeted by heavy weapons.

What about mechs?

**Comment by joesinghaus** [comment]
![type chooser](https://user-images.githubusercontent.com/18185704/40648765-7e983f96-632f-11e8-8a4b-8bd501eb8bb5.png)
I think this (visible in edit mode) would be a good place to put the type choice for the "ship" sheet, instead of hiding it in the options menu.

**Comment by PanzerUXI** [comment]
Mechs are pretty much ships IIRC.

**Comment by PanzerUXI** [comment]
So with this approach, the tabs **Character**, **Vehicle**, **Drone**, **Faction**...and Vehicle has drop-down locally to switch from Ship to Mech to Custom (for Eob)?

**Comment by joesinghaus** [comment]
Yep, that seems the most sensible organisational approach, except that the title of the vehicle tab will change according to the dropdown option.

> Do we just fold Drone into that list since its mechanical too?

Drones *are* somewhat similar to the rest, but they have more profound differences. Don't know about this one. I think drones should be separate.

> Regardless, we'll eventually run into the guy who has a ship, a drone and a mech, and doesn't want 3 sheets to control them all :)

Then we can tell this guy to accept the harsh realities and just use 3 sheets, instead of bloating every single sheet with redundant fields. We're talking about effectively multiplying the ship sheet by 3 to make some extremely minor cosmetic changes.

**Comment by PanzerUXI** [comment]
Hah, Im just saying I can see the ticket now. "Why u make me Make 3 sheets for my stuff. lame."

**Comment by joesinghaus** [comment]
(Probably) resolved by 821567a.
