### ISSUE TITLE
Attack rolls while using First edition skill list.

### ISSUE THREAD

**Issue by Shotty4Life** [Karlinator/roll20-character-sheets#5]
Hello. 

I noticed that since the sheet was updated to version 1.6, you added an option to use First edition skill set optionally. Personally, I prefer the First edition skill list, so this is great. 

Buuut as it happens, attack rolls are broken when using the First edition skills option. The attack rolls always default to using Revised edition "Shoot" skill. Tested this by jumping between the two skill list settings and changing combat related skill levels. While First edition skill list was active, it did not matter which skill was selected for a weapon, it always used what ever skill level I had left for Shoot skill in Revised edition settings.

I probably should also mention: I noticed some weird behavior from the weapons skill selection drop-down menu. When I create a weapon (add a new row under weapons) while using First edition skill list, it always shows Revised edition list for a second, before updating to First edition skill list. Don't know if that "lag" (I guess) has anything to do with the issue.

**Comment by Karlinator** [comment]
Thanks for bringing this up. I located the bug and fixed it. The fix should go live early next week (typically Monday/Tuesday depending on you time zone) when Roll20 approves pull requests.

The delay before it switches to the first edition skill list is unrelated but unavoidable because of how Roll20 works. It needs to be forced to run some things, and that only happens after a field in the repeating section is updated.
