### ISSUE TITLE
sheet version text hasn't updated since 2.2.0

### ISSUE THREAD

**Issue by svmnotn** [Karlinator/roll20-character-sheets#58]
Not sure how to fix it, or if anyone else has noticed but the version text at the bottom of the sheet still says `v2.2.0`. I even created a brand new game, made a character sheet, and when I checked it still said `v2.2.0`.
Kind of a nitpick, but since that is the only version information I can find on the sheet itself, aside from the very obvious changes to it, it is kind of weird for it to not update correctly.

**Comment by Karlinator** [comment]
So that was a fun trek through the sheet version upgrade code in the worker. Turns out there was a missing callback causing the function to terminate early after making all the requisite changes for 2.3.1 (the last version to require upgrade code) but before getting to the step of writing the new version to the attribute. 

Fix'd and will be included in 2.4.1
