### ISSUE TITLE
Magic uncommitted effort has the MAXIMUM_EFFORT_DESC which does not apply to it

### ISSUE THREAD

**Issue by svmnotn** [Karlinator/roll20-character-sheets#59]
I could create a new description that does, or just delete that, but I'm not sure which way we want to go about it.

**Comment by Karlinator** [comment]
Good spot. That's a holdover from early in development when I wanted to make it calculate the effort just like the psionic tab does, and the code was originally copy-pasted from there. I'm inclined to just delete it because Effort is class-specific to some Adepts and I think it varies, but if you can come up with a formula to put there (or on the "total effort" field) then go ahead.

**Comment by svmnotn** [comment]
I was thinking of just making the description something along the lines of `Total - Current - Scene - Day` which is literally what the math is, I'm sure that there may be an actual formula but for my use case I would prefer for it to stay as is. So I think just removing it will be fine, at least it can't cause confusion about why it doesn't do what it says, if it doesn't say anything

**Comment by Karlinator** [comment]
Yes, `Total - Current - Scene - Day` does seem a tad redundant given the layout of the fields and how simple that is. I'll take it out.
