### ISSUE TITLE
Missing ability fields for new character sheet

### ISSUE THREAD

**Issue by gshrikant** [Karlinator/roll20-character-sheets#89]
For some reason the text fields for STR, DEX and CON abilities just doesn't show up when creating a new character even without any API scripts being enabled (sheet settings below).

![image](https://user-images.githubusercontent.com/3136213/92985558-9d3cb900-f468-11ea-969a-aef4cef41348.png)

![image](https://user-images.githubusercontent.com/3136213/92985574-c2c9c280-f468-11ea-93de-d918a047b709.png)

**Comment by Karlinator** [comment]
This is the same as #88, and I've tried to get Roll20 to push out the fix sooner, but to no avail.

If you turn on and then off again the options for "AI Character" and "Transhuman Characters", that should fix it.

Essentially, it thinks the character is supposed to be an AI, which uses the stats of the Shell it occupies instead of rolled stats. Toggling those options on and off again will make it realise it isn't.

Expect the fix to be rolled out by tuesday/wednesday/whenever Roll20 gets around to it.

**Comment by Karlinator** [comment]
Fix is now deployed!
