### ISSUE TITLE
Ship hardpoints can't be adjusted

### ISSUE THREAD

**Issue by MartyMcBuzzard** [Karlinator/roll20-character-sheets#92]
On the "ship" character sheet, the number of hardpoints can't be adjusted. It doesn't auto-adjust to the number of weapons installed, either.

**Comment by Karlinator** [comment]
Sorry I haven't gotten to this, but I am unable to reproduce the issue. The sheet does (should) calculate remaining hardpoints on every change in the weapons list. The inability to manually adjust that number is intentional (as it is a simple sum).

Can you check if you still have the issue? If so, there might be an issue with the data in that sheet, and a subsequent issue in how the sheet handles that unexpected data.

**Comment by MartyMcBuzzard** [comment]
It appears I was mistaken. 
I assumed that the first number of the "5/10" was the number of hardpoints in use, but it shows the number _remaining_. Perhaps the addition of that word (remaining) would make it more clear?

**Comment by Karlinator** [comment]
Moved to a Usability issue.

"Hardpoints Remaining" doesn't really fit (it breaks into two lines, which isn't the end of the world I suppose). How about "Free Hardpoints"?
